### PR TITLE
Feature to make the current day appear in a clearer way and a red cir…

### PR DESCRIPTION
**Pull request by libanista**
…cle to replace the number label on the summary rows (mouse on click on the circle starts a little animation)

### CODE REVIEW

**Comment by ssaring** [comment]
Thanks for the Pull Request, I'll review it ASAP. 

The changeset is huge, the permissions of almost all files have been changed. Was this an accident or your intention? If an accident, then it would be great if you could cleanup this PR.

**Comment by libanista** [comment]
Sorry for the mess,
It must have been Eclipse for sure. I had some troubles running the app. Only two files were really modified. I will make another commit ASAP. 

Thank you for your time.

**Comment by libanista** [comment]
I have just committed a less modified version. Hope it works for you.

**Comment by ssaring** [comment]
Thanks for your update, now the changes are a bit clearer. However, there are still issues, here are some comments:

* The changeset still contains same archive files which must not be commited to the VCS!
* I don't see any user value for the red circle and the animation in the summary cells. You've also removed the week number labels, these are required for many users.
* The current day should be better identifiable in the calendar view - I agree. But I think that your solution does not matches the L&F of the application.
* You should use CSS for styling in the CalendarSummaryCell class and lambda expressions for the event handlers.

Sorry, but this pull request can't be merged to the master currently. There must be a real user value and the problems above needs to be fixed.

**Pull request closed without merging**
