### PR TITLE
Update Leaflet & new Map option

### PR DESCRIPTION
**Pull request by ThomasDaheim**
Me again :-)

Two changes:

1. updated Leaflet to v1.6.0 (various fixes and performance improvements)
1. added a `val mapOptions: String = ""` to MapConfig so that additional options can be passed to the map

The second change isn't really something I couldn't live without. I could always do something like `myMap.options.worldCopyJump = true;` later on via execScript. Also, its about the most simple implementation I could think about. A list of string or a map of variable / value pairs would also work.

### CODE REVIEW

**Comment by ssaring** [comment]
Thanks for the contribution, sound interesting!
I hope to find some time at the next weekend to review your PR.

Bye, Stefan

**Comment by ssaring** [comment]
Hi Thomas, 

I've just reviewed and merged your PR to master and made some minor improvements there (Changelog etc.). 
During review I decided to remove the mapOptions parameter from MapConfig for several reasons: 

- it's undocumented and not clear for the LeafletMap library user how to use it
- it's just appended to the init script in `LeafletMapView#executeMapSetupScripts`, it's not even a separate parameter in the map initialization - so it's usage is quite error prone
- it's not used anywhere - even not in test code, it would be a good example

I understand your demand for map customization, I hope you can live with that decision. If you can provide a better solution, please file it as a separate PR.

Bye, Stefan

**Comment by ThomasDaheim** [comment]
Hi Stefan,

that's fine with me! I can understand that changing options of the map shouldn't be something that is easy to do. The chance of breaking things is too high...

As I said above, I can easily achieve the same result afterwards via js:

`myMap.options.worldCopyJump = true; myMap.options.zoomAnimation = false; myMap.options.preferCanvas = true;`

Bye, Thomas

**Comment by ssaring** [comment]
Nice to hear.

**Pull request merged**
