### PR TITLE
Correct French typo

### PR DESCRIPTION
**Pull request by eliovir**
Forgotten unbreakable spaces (\u00A0) and unneeded upper case.

### CODE REVIEW

**Comment by ssaring** [comment]
I'm sorry that I have to revert this pull request with pull request #3, but there are multiple errors with the provided translation update. Please check the details in PR #3.

**Comment by ssaring** [comment]
Could you please provide your name with the fixed translation? I would like to add it to the contributor list (if you want to).

**Comment by eliovir** [comment]
I'm sorry that I've made mistakes.
In order to see what they are, I tried to compile sportstracker with
```
sudo apt install openjfx openjfx-source
git clone https://github.com/eliovir/sportstracker.git
cd sportstracker
git checkout -b i18n-fr origin/i18n-fr
mvn package
```
but did not succeed. I never developed on JavaFX, maybe some dependencies are missing.
```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ st-exerciseviewer ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] sportstracker/st-exerciseviewer/src/main/java/de/saring/exerciseviewer/gui/EVMain.java:[6,8] 1. ERROR insportstracker/st-exerciseviewer/src/main/java/de/saring/exerciseviewer/gui/EVMain.java (at line 6)
	import javafx.scene.control.Alert;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^
The import javafx.scene.control.Alert cannot be resolved
```

Could you attach some screenshot to help me correct my changes?
Thanks

**Comment by ssaring** [comment]
You need at least Java 8u40 as documented in the ReadMe, the Alert and other classses have been introduced in this release.

If you are using Ubuntu I suggest you to install the 'oracle-java8-installer' package from the PPA https://launchpad.net/~webupd8team/+archive/ubuntu/java. 
The OpenJDK/JFX packages from the official repositories are mostly out of date.

**Pull request merged**
