### PR TITLE
Exercise viewer: add colored slopes

### PR DESCRIPTION
**Pull request by batzkass**
Hi, so I have done the code for this feature. To enable colored slope, just show an altitude graph with distance as bottom axis.
I'm totally new to kotlin and jfreechart, so you definitely should check the code I wrote. However, I tested all graph configurations and it seems to work very well without bugs.

### CODE REVIEW

**Comment by ssaring** [comment]
Wow, that was fast. Sounds interesting. It will take some day before I'll find some time for review and integration. Could you please attach a screenshot, just for getting an idea for your solution?
BTW: Is there a kind of legend where the user can see what the colors mean?

Bye, Stefan

**Comment by batzkass** [comment]
Here are the screenshots of the "final" version, for left and right axis:
Screenshot_20190507_213202
Screenshot_20190507_213142

Adding a legend is mandatory, but I find that jfreechart is very painful as soon as you need to tweak elements. For example, drawing squares in the chart container coordinates system, customizing legend items... Do you have an idea ?

**Comment by ssaring** [comment]
The screenshots look great - very interesting feature.
IMHO this kind of graph makes only sense for altitude data, not for heart rate, temperature and so on - what do you think?

For the legend: what about this workaround? There could be a "Altitude Legend Info" button on the right edge of the axis comboboxes. When the user presses it, then a info dialog or tooltip is shown which explains all the colors.

**Comment by batzkass** [comment]
At this moment the feature is only activated when you plot altitude vs distance. Others than altitude have no sense to me too, I'm just wondering about altitude vs time which is disabled for now.

For the colorscale, if you can do it in a new window, can't you do almost the same in a new widget of the graph window ?

**Comment by ssaring** [comment]
If the feature is only active for the combination altitude vs distance, that's great.

What do you mean by "a new widget for the graph window"?

**Comment by batzkass** [comment]
I don't know javafx at all, but I'm learning now and I'm working on the legend. By widget, I mean graphical widget, added below or above the graph. I'm currently creating an HBox with colored rectangles for the legend. It may fit our needs.

**Comment by ssaring** [comment]
Sounds interesting. It would be good when the UI does not gets more nervous by switching the layout when the user changes the axis types, e.g. between altitude and heart rate.

**Comment by batzkass** [comment]
Yes, to avoid this "nervosity" my first attempt is to reserve a little space: empty when no legend is needed, filled with legend otherwise. But I plan to put the legend over the graph... if possible.

**Comment by batzkass** [comment]
Currently I'm pretty satisfied with that:


And in blue:


When you don't display the slope, legend disappears without moving nor resizing graph:


And finally, only necessary legend element are displayed (the first data point is always wrong, altitude way to small, probably due to my recorder)

**Comment by batzkass** [comment]
Here we are, best I can do:
Screenshot_20190509_235219 
For me its stable and works.

**Comment by batzkass** [comment]
I have pushed everything in my fork. As I find this view nice and useful, I took the liberty of setting altitude vs distance as default view :-P

**Comment by ssaring** [comment]
Great work! The version I like most is when the altitude legend is displayed above the diagram. When displayed inside the diagram it can interfere with the graph itself.
When the altitude is not displayed, it would make sense to use this space for the diagram. I can try to tweak that if you don't have an idea how to realize.

Do you think it's good to display only the colors in the legend which are in use? I would always show all of them, then the user can see which ascent degrees are not part of the exercise.

You've said that the altitude vs distance is the new default? This is maybe the most interesting option for the user when his watch records that data. But there are many watches without GPS and altitude data, they record the heartrate only.
Your new default sounds OK, but we should fall back to heartrate when no altitude is present and to time when no distance is present.

BTW: how do you test that the colors of the ascent degrees are correct?

**Comment by batzkass** [comment]
> Great work! The version I like most is when the altitude legend is displayed above the diagram. When displayed inside the diagram it can interfere with the graph itself.
> When the altitude is not displayed, it would make sense to use this space for the diagram. I can try to tweak that if you don't have an idea how to realize.

I agree, but adapting the graph size is what I thought you was talking about with "nervosity". As we talk about that I think that the scale for the altitude is not well suited. If I train from 2000m to 3000m, I will have 2/3 of the height loss with no info. Maybe we should use [ min(alt) - 0.1xDelta_alt ] -> [ max(alt) + 
0.1xDelta_alt ] . This way, we would be sure that we always keep enough space at the graph top for the slope scale.

> Do you think it's good to display only the colors in the legend which are in use? I would always show all of them, then the user can see which ascent degrees are not part of the exercise.

Both are ok, not important to me.

> You've said that the altitude vs distance is the new default? This is maybe the most interesting option for the user when his watch records that data. But there are many watches without GPS and altitude data, they record the heartrate only.
> Your new default sounds OK, but we should fall back to heartrate when no altitude is present and to time when no distance is present.

It's already the case as I implemented it. I have just swapped the order of [time, distance] in the dropdown list: if distance is enabled, it will be added at position 0 of the dropdown so will be default.

> 
> BTW: how do you test that the colors of the ascent degrees are correct?

I'm not sure to get the sense of this question. Is that for compilation test sequence purpose ? The slope is just Dy/Dx = D_alt/D_dist, no reason to make some mistakes. Also, to avoid getting very thin vertical lines for each gps or baro glitch, I only keep one data per 100m, it's like filtering to avoid noise on signal.

To finish, I have to say that I totally neglected the fact that SportsTracker can be used with imperial units, this may need a check.

**Comment by ssaring** [comment]
> I agree, but adapting the graph size is what I thought you was talking about with "nervosity". As we talk about that I think that the scale for the altitude is not well suited. If I train from 2000m to 3000m, I will have 2/3 of the height loss with no info. Maybe we should use [ min(alt) - 0.1xDelta_alt ] -> [ max(alt) +
0.1xDelta_alt ] . This way, we additionaly would be sure that we always keep enough space at the graph top for the slope scale.

Yes, the nervosity issue was my initial thought. But seeing your example screenshots, the version where the legend sits above the diagram is much cleaner and more readable. Would it be possible to switch back this PR to this variant?
About the loss of diagram space: for some reason this is only the case when the altitude is vs distance, it's not the problem when vs. time. This seems to be a bug, which has not been solved yet.

> Both are ok, not important to me.

Same here: would it be possible to switch back this PR to show all colors?

> I'm not sure to get the sense of this question. Is that for compilation test sequence purpose ?

I mean both unit tests and the manual tests for e.g. recordings where you know the slope degrees. Does this match?
I agree, the slope calculation is quite easy. But this could be extracted to a separate class (e.g. in existing CalculationUtils ?) and become unit tested. Although this looks simple there can occur errors when values are 0 or missing or negative ...

**Comment by batzkass** [comment]
> > I agree, but adapting the graph size is what I thought you was talking about with "nervosity". As we talk about that I think that the scale for the altitude is not well suited. If I train from 2000m to 3000m, I will have 2/3 of the height loss with no info. Maybe we should use [ min(alt) - 0.1xDelta_alt ] -> [ max(alt) +
> > 0.1xDelta_alt ] . This way, we additionaly would be sure that we always keep enough space at the graph top for the slope scale.
> 
> Yes, the nervosity issue was my initial thought. But seeing your example screenshots, the version where the legend sits above the diagram is much cleaner and more readable. Would it be possible to switch back this PR to this variant?

Sure, next week.

> About the loss of diagram space: for some reason this is only the case when the altitude is vs distance, it's not the problem when vs. time. This seems to be a bug, which has not been solved yet.
> 
> > Both are ok, not important to me.
> 
> Same here: would it be possible to switch back this PR to show all colors?

Sure, next week.

> 
> > I'm not sure to get the sense of this question. Is that for compilation test sequence purpose ?
> 
> I mean both unit tests and the manual tests for e.g. recordings where you know the slope degrees. Does this match?

Sorry, still can't get what you mean by "does this match?". Slopes data matches topo data if this is what you mean.

> I agree, the slope calculation is quite easy. But this could be extracted to a separate class (e.g. in existing CalculationUtils ?) and become unit tested. Although this looks simple there can occur errors when values are 0 or missing or negative ...

Yes, or even worst, infinite (vertical) slope :-P

**Comment by ssaring** [comment]
Short question: is this interesting feature still in work?

**Comment by batzkass** [comment]
Sorry, I finally found some time to do what you requested in your message (10 may). The feature seems to work properly, however you may need a little bit of work to move some code and validate data (CalculationUtils as you mentionned).

**Comment by ssaring** [comment]
The initial tests looked very good. There are still some minor issues which I will take a look at in the next days - I will update them in the origin repo.

Thanks a lot for this nice contribution!

Bye, Stefan

**Comment by ssaring** [comment]
@batzkass  I've done some minor improvements for the altitude slopes in the master branch. The slopes legend also takes no vertical space now, when it's not needed.

Question: have you tested that the proper slope degrees are shown on the tracks you know quite good? I've tested it with some exercises of tracks, where the slopes are 18 to 20%. But the diagram does not show any slopes in the color for > 15%. That's confusing...

Bye, Stefan

**Comment by batzkass** [comment]
Hi,
With the version on my fork I have no problem: 
Screenshot_20190705_094821

**Comment by ssaring** [comment]
OK, if you think so. On my cycling / running tracks it feels like there are 2 or 3 percent in each slope missing. But I don't have real values for validation.

I've done with my improvements on this feature, I hope the result is OK for you too.

It's time to release SportsTracker 7.7.0, there are a lot of nice changes now.

**Comment by batzkass** [comment]
Just to be sure, on the altitude vs distance graph (XY time series), is it
altitude vs horizontal (on a flat earth) distance ? Or is it altitude vs
distance traveled ? In this second case the slopes would be effectively
wrong, and I'm afraid its the case and you have to replace here
https://github.com/ssaring/sportstracker/blob/master/st-exerciseviewer/src/main/kotlin/de/saring/exerciseviewer/gui/panels/DiagramPanelController.kt#L774
and L775 by:

> val Dd = (nextDataItem.x.toDouble() - dataItem.x.toDouble())*1000 //meters
> val Dy = nextDataItem.y.toDouble() - dataItem.y.toDouble() //already
> meters
> val Dx = sqrt(Dd*Dd - Dy*Dy) //replace sqrt by kotlin equivalent
>
val slope = abs(Dy/Dx)*100 // in %

Let me know if it works,
François

Le ven. 5 juil. 2019 à 21:21, Stefan Saring <notifications@github.com> a
écrit :

**Comment by ssaring** [comment]
It's the second option, the travelled distance. I'll try your change later, going cycling now ;)Am 05.07.2019 11:58 nachm. schrieb Francois Kneib <notifications@github.com>:Just to be sure, on the altitude vs distance graph (XY time series), is it

altitude vs horizontal (on a flat earth) distance ? Or is it altitude vs

distance traveled ? In this second case the slopes would be effectively

wrong, and I'm afraid its the case and you have to replace here

https://github.com/ssaring/sportstracker/blob/master/st-exerciseviewer/src/main/kotlin/de/saring/exerciseviewer/gui/panels/DiagramPanelController.kt#L774

and L775 by:



> val Dd = (nextDataItem.x.toDouble() - dataItem.x.toDouble())*1000 //meters

> val Dy = nextDataItem.y.toDouble() - dataItem.y.toDouble() //already

> meters

> val Dx = sqrt(Dd*Dd - Dy*Dy) //replace sqrt by kotlin equivalent

>

val slope = abs(Dy/Dx)*100 // in %



Let me know if it works,

François



Le ven. 5 juil. 2019 à 21:21, Stefan Saring <notifications@github.com> a

écrit :

**Comment by ssaring** [comment]
I've tested your new slope calculation on some recorded exercises an compared the generated chart colors with the old slope calculation. I don't see any difference in the resulting chart - they look completely identical. 

I assume you expect different results, right?

**Comment by batzkass** [comment]
I wasn't sure about the différence on the graph. For low slopes (the slopes
we can typically ride, <20%), the hypotenuse (ride distance) ≈ the
horizontal distance. As the sample is subsampled (at ≈100m) and as we don't
use a continuous scale (but rather 5 ranges) I'm not really surprised that
the result is exactly the same. It just means that the tiny difference
between the 2 options is way below our scale precision.
Anyway, better do the new option which is geometrically exact.

Nb: the inconsistency of slopes compared to ones you were expecting may be
explained by the x-axis subslampling (≈ smoothing).

Le sam. 6 juil. 2019 à 21:34, Stefan Saring <notifications@github.com> a
écrit :

**Comment by ssaring** [comment]
OK, makes sense. I've adopted your improved slope calculation, it's allready in the master branch.

I've thought this feature is done now, unfortunately I've found a bug. The slope percentage calculation does only work properly when using the metric unit system. When the user switches to the english unit system (miles & feets), the percentage values are completely wrong. In a test exercise file the altitude chart is mostly yellow for metric units, but mostly red for english units.

@batzkass Could you please take a look at this bug?

**Comment by batzkass** [comment]
I thought I already told you about that, but can't found were. Anyway, I'll fix it but it seems that you didn't pushed the correct slope calculation in master. Could you please do it before to avoid collides ?

**Comment by ssaring** [comment]
Ooops, I've forgotten that - sorry. It's pushed now.

**Comment by ssaring** [comment]
@batzkass Just wanted to let you know, that I allready fixed the english unit system support (to avoid work duplicates). It's allready in master and also pushed :)

**Pull request merged**
