### PR TITLE
Added missing calculations for Fenix 2 and refactored summary calculation

### PR DESCRIPTION
**Pull request by BitSchupser**
Hi,

I added the calculation of heart rate and altitude summary which was 0 when importing from Garmin Fenix 2.

After that I experienced a noticeable performance issue when importing FIT files due to the calculation of the summaries over the samples. I did a refactoring to ensure that the algorithm iterates over the samples only once to calculate the summaries. Furthermore this refactoring moved every parameter to its own class (separation of concerns) and improved testability.

Finally I created an exercise builder that allows to configure EVExercises fluently when writing tests (my main motivation behind this was to play around with Java's new lambdas ;-)).

Just take a look onto my changes, if you their ok, include them. If not feel free to edit them as you like or give me feedback.

Greets
Alex

### CODE REVIEW

**Comment by ssaring** [comment]
Hi Alex,

Thanks for you contribution for the special handling of Fenix exercise files! I've just reviewed your PR and have a few comments:

* There is already a calculation of the altitude summary. You mentioned that it was 0 for the Garmin Fenix exercises - is there something special in the FIT files for this model?
* You have done the refactoring due to performance issues when calculation the summary. There should be no problems when calculating the values after collecting all the data in the listener, as already done for the other summary calculations. Or is the calculation afterwards not possible in your case?
* Would it be possible to add an full-exercise test for a specific Fenix (2) exercise file (as done for the other models)? Then we can always test the specialities of these exercises, also after refactorings or updates of the FIT library.
* Your solution with the decorators, aggregators, ... uses a lot of nice design patterns, which all makes sense in larger scale environments. Here we are just facing the internal structure of one simple exercise parser class, which was quite simple (IMHO) before the refactoring. The new solution is technically quite interesting, but more complex and complicated. I think the code is easier to understand and maintain when all the summary calculations are done afterwards in a few very simple internal methods (much less code). These methods can even be simplified by using lambdas and the Stream API.
* The idea of the builders for the exercise files is very nice. If we introduce them, then we would need to complete the builders to support all exercise attributes (currently just an subset), add JavaDocs, improve the code style, ... Otherwise we will have a mixture of the class and builder style in the future. We then also need to extend them on all changes to the EVExercise classes too. Currently all parser implementation are using unit tests for complete exercise files, so the builders are no benefit for them. So I think the introduction of the builders is too much effort for the small usage.

What do you think - are there any issues and reasons I've missed or would it be possible to transform your changes to the previous parser style and the missing exercise test? 

Bye, Stefan

**Comment by BitSchupser** [comment]
Hello Stefan,

thanks for your comments.

> There is already a calculation of the altitude summary. You mentioned that it was 0 for the Garmin Fenix exercises - is there something special in the FIT files for this model?

Sorry I was wrong in my comment - altitude is fine. I added summary calculation for heart rate max/avg and speed max.

> You have done the refactoring due to performance issues when calculation the summary. There should be no problems when calculating the values after collecting all the data in the listener, as already done for the other summary calculations. Or is the calculation afterwards not possible in your case?

Sure it is possible. After I added the summary calculations mentioned above I observed that the app was blocked for roughly a second when loading the fit file and doing the calculations. I think this is not a big issue but noticable (you can reproduce it when you use revert to e19f905 in my pull request). 

> Would it be possible to add an full-exercise test for a specific Fenix (2) exercise file (as done for the other models)? 

This was my plan, I will send a separate pull request as soon as I have recorded an appropriate FIT file.

> Your solution with the decorators, aggregators, ... uses a lot of nice design patterns, which all makes sense in larger scale environments. [...]

My main motivation here was to play around with Java (I come from Java but did C# only for the last 3 years), I also sensed that it could be a little overengineered here. If you only apply b12fb7d, 713dc54 and e19f905 you'll get the extensions for Fenix 2 as internal methods without the bloated refactoring (I added all functionality in these changesets and refactored afterwards).

> [...] builders for the exercise files [...] So I think the introduction of the builders is too much effort for the small usage.

Aggree. If we do not use the refactoring above, we also do not need the builders.

> [...] would it be possible to transform your changes to the previous parser style and the missing exercise test?

As mentioned above, just merge the first three changesets and you'll get the functionality for Fenix 2 implemented in the previous parser style.
For the missing exercise test I'll send you a separate pull request.

Regarts, Alex

**Comment by ssaring** [comment]
Hi Alex,

great to hear that it's OK for you to stick to the KISS (keep it stupid simple) paradigm. I also know that it's nice to use projects as a playground for good and nice ideas, but it's important to check whether this makes sense on the long-term.

I would not like to take parts of your pull request and merge them as my changes in the master branch. Could you please create a new pull request with the test file and the needed parser changes, once you recorded that Fenix file? Then it would be merged as your contribution.
Is it OK for you to add your name / email (unknown) to the list of authors?

Bye, Stefan

**Comment by ssaring** [comment]
This Pull Request is not needed anymore, the issue has been solved by Pull Request #8.

**Pull request closed without merging**
