### PR TITLE
LeafletMapView improvements for pull request Remove-Layers #178

### PR DESCRIPTION
**Pull request by ssaring**
* improved LeafletMapView method for deleting displayed markers and tracks
* removed MarkerInterface, no current use cases (can be added when in use)
* updated documentation

### CODE REVIEW

**Comment by ssaring** [comment]
@ThomasDaheim I've added some minor improvements for your PR here, I hope it's OK for you. I think the JavaScript code handling is much easier now. 

I've also removed the MarkerInterface for now, I don't like to add code extensions which are not in use. A Marker interface might be introduced when the API would also allow the usage of other marker types. This is not the case yet.

**Comment by ThomasDaheim** [comment]
@ssaring : I had added the MarkerInterface exactly BECAUSE I already use it in GPXEditor! That was the whole point of it... I have already added a handful of own markers "on the fly" to LeafletMapView. Unfortunately, there is now way to extend LeafletMapView from the outside in this case because there is now way to extend ColorMarker.

**Comment by ThomasDaheim** [comment]
If OK with you I would add this again with my next pull request - not done yet with extending the LeafletMapView :-) Also, I think that addStyle doesn't yet handle all cases...

**Comment by ThomasDaheim** [comment]
I see that you also removed addScript and addStyle from LeafletMapView. Unfortunately, without those two LeafletMapView can't be reused / extended by anyone else.

**Comment by ssaring** [comment]
@ThomasDaheim As long as the methods as addScript and addStyle are used in your project only I would not like to add it to the component. The class is open now and can be extended. The method execScript() is protected too, so you should be able to add them in your subclass. 
I would add them to LeafletMapView when it is also in use by the application (or the demo), that's currently not the case.

**Comment by ssaring** [comment]
@ThomasDaheim OK, I see that you depend on that interface. So I'll added it with pull request #180 (it's just named Marker).

**Pull request merged**
